/* Toroidal Tic-Tac-Toe - board, toroidal wrapping, winning lines.
 * Platform independent: no Pebble APIs. */
#ifndef TTT_BOARD_H
#define TTT_BOARD_H
#include <stdint.h>
#include <stdbool.h>

#define TTT_ROWS 3
#define TTT_COLS 3
#define TTT_CELLS 9
#define TTT_NUM_LINES 12

/* Logical player roles. Also used as cell contents (0 = empty).
 * These are roles, NOT glyphs and NOT Human/Computer. */
typedef enum { TTT_EMPTY = 0, TTT_PLAYER_1 = 1, TTT_PLAYER_2 = 2 } TttPlayer;

typedef struct { uint8_t cell[TTT_CELLS]; } TttBoard;   /* index = row*3+col */
typedef struct { uint8_t cell[3]; } TttLine;

/* Toroidal coordinates */
int ttt_wrap(int v);                       /* any int -> 0..2 */
int ttt_cell_index(int row, int col);      /* wraps both */
int ttt_cell_row(int index);
int ttt_cell_col(int index);
int ttt_cell_next(int index);              /* selection cycle A..I..A */
int ttt_cell_prev(int index);
TttPlayer ttt_other_player(TttPlayer p);

/* Board */
void ttt_board_init(TttBoard *b);
TttPlayer ttt_board_get(const TttBoard *b, int row, int col);   /* wraps */
TttPlayer ttt_board_get_index(const TttBoard *b, int index);
bool ttt_board_is_valid_move(const TttBoard *b, int index);
bool ttt_board_place(TttBoard *b, int index, TttPlayer p);
int  ttt_board_count_empty(const TttBoard *b);
bool ttt_board_is_full(const TttBoard *b);

/* The 12 unique toroidal lines (generated by wrapped movement in 4
 * directions from every cell, de-duplicated). */
const TttLine *ttt_lines(void);
TttPlayer ttt_board_winner(const TttBoard *b, int *line_index_out); /* TTT_EMPTY if none */
int  ttt_board_count_lines_for(const TttBoard *b, TttPlayer p);     /* simultaneous lines */
int  ttt_board_find_winning_move(const TttBoard *b, TttPlayer p);   /* cell or -1 */

#endif
